CREATE TABLE autorizacoes_receitas_retroativas (
    id_autorizacao BIGINT NOT NULL AUTO_INCREMENT,
    id_inst BIGINT NOT NULL,
    id_solicitante BIGINT NOT NULL,
    id_auditor BIGINT NULL,
    id_receita BIGINT NULL,
    data_receita DATE NOT NULL,
    dias_atraso SMALLINT NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    status ENUM('PENDENTE','AUTORIZADA','UTILIZADA') NOT NULL DEFAULT 'PENDENTE',
    autorizado_at TIMESTAMP(6) NULL,
    pdf_gerado_at TIMESTAMP(6) NULL,
    utilizado_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id_autorizacao),
    CONSTRAINT fk_aut_rec_ret_inst FOREIGN KEY (id_inst) REFERENCES instituicoes (id_inst) ON DELETE RESTRICT,
    CONSTRAINT fk_aut_rec_ret_solicitante FOREIGN KEY (id_solicitante) REFERENCES users (id_user) ON DELETE RESTRICT,
    CONSTRAINT fk_aut_rec_ret_auditor FOREIGN KEY (id_auditor) REFERENCES users (id_user) ON DELETE SET NULL,
    CONSTRAINT fk_aut_rec_ret_receita FOREIGN KEY (id_receita) REFERENCES transacoes_receitas (id_receita) ON DELETE SET NULL,
    INDEX idx_aut_rec_ret_status_created (status, created_at),
    INDEX idx_aut_rec_ret_inst_status (id_inst, status),
    INDEX idx_aut_rec_ret_receita (id_receita)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
